apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "tracetest-shipyard"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "sequence1"
          tasks:
            - name: "test"
            - name: "evaluation"
              properties:
                timeframe: 5m
            #- name: "deployment"
