apiVersion: v2
actions:
  - name: "Run tracetest"
    events:
      - name: "sh.keptn.event.test.triggered"
    tasks:
      - name: "Run tracetest"
        # When testing to guarantee new images are pulled. Do not use in production.
        imagePullPolicy: "Always"
        files:
          - '/files'
        image: "gardnera/python:tracetest_with_prometheus"
        cmd:
          - "python3"
        args:
          - '/keptn/files/app.py'
