apiVersion: v2
actions:
  - name: "Run tracetest"
    events:
      - name: "sh.keptn.event.test.triggered"
    tasks:
      - name: "Run tracetest"
        #imagePullPolicy: "Always"
        files:
          - '/files'
        # Image used with v2+ logic (pushing metrics to Prometheus)
        image: "gardnera/python:tracetest_with_prometheus"
        # Image used with v1 logic
        #image: "gardnera/python:tracetest"
        cmd:
          - "python3"
        args:
          - '/keptn/files/app.py'
