apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.test.triggered
      requests:
        - >-
          curl --header 'Accept: application/json' --header 'xaror79553@lodores.com: 0Y2elLSCdWJ7OlPXNHaY883C' --request GET https://keptn-sp.atlassian.net/rest/api/3/events
      subscriptionID: 3f9d0561-f014-4412-a713-39537ef8b706
      sendFinished: true
      sendStarted: true
