name: POST import pokemon
trigger:
  type: http
  httpRequest:
    url: http://demo-pokemon-api.demo/pokemon/import
    method: POST
    headers:
    - key: Content-Type
      value: application/json
    body: '{ "id": 52 }'
specs:
- selector: span[name = "POST /pokemon/import"]
  assertions:
  - tracetest.span.duration <= "30ms"
  - http.status_code = 200
  - http.response.body contains 52
- selector: span[name="queue.synchronizePokemon send"]
  assertions:
  - messaging.payload contains 52
